// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Transition = 0;

var CSSTransition = 0;

var TransitionGroup = 0;

exports.Transition = Transition;
exports.CSSTransition = CSSTransition;
exports.TransitionGroup = TransitionGroup;
/* No side effect */
