// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Index = require("react-transition-group/index");

function make(appear, enter, exit, children) {
  var tmp = { };
  if (appear !== undefined) {
    tmp.appear = Caml_option.valFromOption(appear);
  }
  if (enter !== undefined) {
    tmp.enter = Caml_option.valFromOption(enter);
  }
  if (exit !== undefined) {
    tmp.exit = Caml_option.valFromOption(exit);
  }
  return ReasonReact.wrapJsForReason(Index.TransitionGroup, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
